// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kejfopmmiyhpxgbfarmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlamZvcG1taXlocHhnYmZhcm1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4Njk1MTIsImV4cCI6MjA2NDQ0NTUxMn0.2YoIY2Uy9ih5Oy-80nZujhD-bDJfFtE7EZS56n7uH5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);